DE8161/Shows feedback portrait card
crdschurch/crds-components pull request #1057
Opened 2021-02-11 20:36 UTC by kellgauthier

## Task 
Per design, portrait cards enlarge on hover. 
Adds hover effect. 

[Design](https://projects.invisionapp.com/d/main?origin=v7#/console/20964701/441631718/preview?scrollOffset=0)
[Rally] (https://rally1.rallydev.com/#/38108142417d/custom/24109743995?detail=%2Fdefect%2F496977932712)
Preview

2021-02-11 21:44 UTC, silasbaur reviewed
@kellgauthier Have you tested what this might look/behave like inside of the carousel component?

2021-02-11 21:44 UTC, dholloran-ample requested changes
@kellgauthier - Animation looks great. I do have one concern about it overlapping content around it (See images below). I was thinking maybe adding `margin`/`padding` to compensate for the shift.

Let me know if that doesn't make sense

## Not Hovered
![screenshot 2021-02-11 at 16 41 22](https://user-images.githubusercontent.com/56852436/107702380-26f6e980-6c88-11eb-9d1a-b7f3ce3fbf1b.png)

## Hovered
![screenshot 2021-02-11 at 16 41 29](https://user-images.githubusercontent.com/56852436/107702385-28281680-6c88-11eb-81ab-01711168f62c.png)

2021-02-12 17:55 UTC, kellgauthier commented
Thank you both for the feedback, I added a `margin` to the `portrait card`, and a `z-index` to the `:hover` state. 

https://user-images.githubusercontent.com/57996315/107804069-76452480-6d31-11eb-8f7c-cdb7e173618b.mp4

2021-02-12 19:31 UTC, dholloran-ample requested changes
@kellgauthier - I left 2 inline comments

2021-02-12 19:31 UTC, dholloran-ample commented on src/components/crds-portrait-card/crds-portrait-card-shows/crds-portrait-card-shows.scss
> +  max-width: 280px;
I try to shy away from `max-width`. Could this width be implemented in Storybook or the container instead of in the component?

2021-02-12 19:31 UTC, dholloran-ample commented on src/components/crds-portrait-card/crds-portrait-card-shows/crds-portrait-card-shows.scss
> +  margin: 30px;
I'm iffy on hard coding the margin to `30px` I tried `margin: 9% 5%;` and it seems to keep it all within the box. 

I'd be ok merging and seeing how it interacts with other items without the margin. I'll leave that up to you.

2021-02-15 16:23 UTC, dholloran-ample approved these changes

2021-02-15 16:45 UTC, merged